"""Changelog renderer.

Produces Keep a Changelog (https://keepachangelog.com) formatted output.
Supports multi-label files — the same file can appear under multiple sections.

Sections (in order): Breaking Changes, Features, Bug Fixes, Refactors,
                     Documentation, Chores
"""

from __future__ import annotations

from datetime import date
from io import StringIO
from pathlib import Path
from typing import TextIO

from .classifier import ChangeLabel, MultiClassifiedChange
from .git_interface import DiffResult
from .llm_summarizer import LLMSummary

_SECTION_ORDER: list[tuple[ChangeLabel, str]] = [
    ("breaking",      "Breaking Changes"),
    ("feature",       "Features"),
    ("bugfix",        "Bug Fixes"),
    ("refactor",      "Refactors"),
    ("documentation", "Documentation"),
    ("chore",         "Chores"),
]


class ChangelogRenderer:

    def render(
        self,
        diff_result: DiffResult,
        classifications: list[MultiClassifiedChange],
        llm_summary: LLMSummary,
        version: str | None = None,
    ) -> str:
        buf = StringIO()
        self._write(buf, diff_result, classifications, llm_summary, version)
        return buf.getvalue()

    def render_to_file(
        self,
        path: str | Path,
        diff_result: DiffResult,
        classifications: list[MultiClassifiedChange],
        llm_summary: LLMSummary,
        version: str | None = None,
    ) -> None:
        Path(path).write_text(
            self.render(diff_result, classifications, llm_summary, version),
            encoding="utf-8",
        )

    def _write(
        self,
        out: TextIO,
        diff_result: DiffResult,
        classifications: list[MultiClassifiedChange],
        llm_summary: LLMSummary,
        version: str | None,
    ) -> None:
        today = date.today().isoformat()
        ver_label = version or f"{diff_result.from_ref}..{diff_result.to_ref}"

        out.write(f"# Changelog\n\n")
        out.write(f"## [{ver_label}] — {today}\n\n")

        if llm_summary.release_summary:
            out.write(f"> {llm_summary.release_summary}\n\n")

        n_files = diff_result.total_files_changed
        n_plus  = diff_result.total_lines_added
        n_minus = diff_result.total_lines_deleted
        out.write(
            f"**{n_files} file(s) changed** · "
            f"`+{n_plus}` additions · "
            f"`-{n_minus}` deletions\n\n"
        )

        # Build label → [files] map — a file can appear in multiple sections
        label_map: dict[ChangeLabel, list[MultiClassifiedChange]] = {
            label: [] for label, _ in _SECTION_ORDER
        }
        for c in classifications:
            for label in c.labels:
                if label in label_map:
                    label_map[label].append(c)

        for label, section_title in _SECTION_ORDER:
            items = label_map[label]
            if not items:
                continue
            out.write(f"### {section_title}\n\n")
            for item in sorted(items, key=lambda x: x.path):
                summary = llm_summary.file_summaries.get(item.path, item.reason)
                out.write(f"- **`{item.path}`** — {summary}\n")
            out.write("\n")

        if diff_result.commits:
            out.write("### Commits\n\n")
            for commit in diff_result.commits[:30]:
                first_line = commit.message.splitlines()[0]
                out.write(
                    f"- [`{commit.short_sha}`] {first_line} "
                    f"_({commit.author}, {commit.date})_\n"
                )
            if len(diff_result.commits) > 30:
                out.write(f"- _… and {len(diff_result.commits) - 30} more commits_\n")
            out.write("\n")

        out.write(
            f"---\n"
            f"_Generated by [difflog](https://github.com/you/difflog) "
            f"using `{llm_summary.model_used}`_\n"
        )